name: Maven Package

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:

  build_test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build and Test with Maven
        run: mvn -B verify --file pom.xml
      - name: Upload JAR Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Package
          path: target/*.jar

  publish-job:
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs: build_test
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Download JAR Artifact
      uses: actions/download-artifact@v4
      with:
        name: Package
        path: staging